### ISSUE TITLE
Email Not Sent

### ISSUE THREAD

**Issue by sciefylab** [TalLannder/beego-ureg#1]
hi man,

I have tried singup then got err 2/12/2018 2:28:54 PM2018/02/12 06:28:54 [signup.go:94][E] SignupController:Post - Got err inserting user to the database:  no LastInsertId available 
and email not sent,
can you help me, please 

regards
rino

**Comment by OnlyLoveOleg** [comment]
@sciefylab not sure how much I can help you since you're getting the error from the ORM. Check https://github.com/astaxie/beego/issues/815 that might help you resolve the issue. If you still having trouble feel free 2 reach out I'll try my best to help you.

**Comment by sciefylab** [comment]
Hi TalLannder,

I have been modofied my controller line 94 and worked perfectly,


```
import (
...
"log"
)

...
_, err = o.Insert(&user)
if err != nil {
    if err.Error() == "no LastInsertId available" {
        log.Println(err)
    } else {
        beego.Error("SignupController:Post - Got err inserting user to the database: ", err)
        flash.Error(signupform.Email + " already registered")
        flash.Store(&this.Controller)
        return
    }
 }
...
```

updated 15-02-2018


thanks you so much, Solved!!
